import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"ChatGPT_TG4Bot") 
SUDO=os.environ.get("SUDO","")
BOT_NAME = os.environ.get("BOT_NAME","Chat GPT")
START_IMG = os.environ.get("START_IMG","https://graph.org/file/25bede556e6f95de9b032.jpg")
STKR = os.environ.get("STKR","")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","ChatGPT_TG4")
# OWNER_USERNAME = os.environ.get("OWNER_USERNAME","ChatGPT_TG4")
SUDO=os.environ.get("SUDO","")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","ChatGPT_TG4")
